---
- hosts: mywebservers
  become: yes
  tasks:
    - name: install java on ubuntu
      apt:
         name: "{{myjavainstalledonubuntu}}"
         state: present
      when: ansible_os_family=="Debian"
    - name: install java on RedHat
      yum:
        name: "{{myjavainstalleonredhat}}"
        state: present
      when: ansible_os_family=="RedHat"