---
- hosts: 172.31.13.171
  become: yes
  tasks:
   - include_tasks: myfile.yml
   - name: instal webserver
     apt:
      name: apache2
      state: present
   - name: i wan to copy index file into node side
     template:
       src: myindex.j2
       dest: /var/www/html/index.html  