---
- hosts: 172.31.13.171
  become: yes
  tasks:
   - include_tasks: myfile.yml

   - name: instal webserver
     apt:
      name: apache2
      state: present

   - name: i wan to copy index file into node side
     template:
       src: myindex.j2
       dest: /var/www/html/index.html  
     
     notify:
       - restarted webserver

   - name: download file and force basic auth
     get_url:
      url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes

   - name: I want to create directory
     file:
         path: /home/ubuntu/mydir1
         state: directory

  handlers: 
   - name: restarted webserver
     service:
        name: apache2
        state: restarted