---
- hosts: all
  become: yes
  tasks:
    - name: i want to install software in ubuntu only
      apt:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"
    - name: i want to start apache2 in ubunt only
      service:
        name: apache2
        state: started
      when: ansible_os_family== "Debian"