---
- hosts: all
  become: yes
  tasks:
    - name: i want to install software in ubuntu only
      apt:
        name: "{{mywebserverpackforubuntu}}"
        state: present
      when: ansible_os_family=="Debian"
    - name: i want to start apache2 in ubunt only
      service:
        name: "{{mywebserverpackforubuntu}}"
        state: started
      when: ansible_os_family== "Debian" 

    - name: I want to install webserver in RedHat only
      yum:
         name: "{{mywebserverpackforredhat}}"
         state: present
      when: ansible_os_family=="RedHat"
    - name: I want to start webserver in RedHat only
      service:
         name: "{{mywebserverpackforredhat}}"
         state: started
      when: ansible_os_family=="RedHat"