- name: copy tomcat_user file into nodes
  template:
     src:  template/myconfiguser.j2
     dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy context file into nodes
  template:
      src:  template/mytomcontext.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy host context file into nodes
  template:
      src:  template/mytomhostcontext.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml