---
# tasks file for mywebrole
- name: i want to install apache2
  apt:
   name: apache2
   state: present
   
- name: i want to create file
  file:
   path: /home/maha/rolefile
   state: touch

- notify:
   - debugvars   